export { default as Intro } from './01-intro/intro'
export { default as Unemployment } from './02-unemployment/unemployment'
export { default as MentalDistress } from './07-mental-distress/mental'
export { default as MentalChart } from './07-mental-distress/mentalchart'
export { default as SmokeSlide } from './08-smoking/smoke'
export { default as SmokingGame } from './08-smoking/smokinggame'
